<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Business</name>
   <tag></tag>
   <elementGuidId>58725adb-9793-4403-9d9b-dd1b822f264c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.BPNpve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Business&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>46333990-4bef-4484-abf5-9246282898a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BPNpve</value>
      <webElementGuid>da593bf6-f459-4937-82f1-13bd971a23dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business</value>
      <webElementGuid>24610a39-4bd2-4aa9-9178-04a2c93ad8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf&quot;]/div[@class=&quot;T4LgNb&quot;]/main[@class=&quot;IKXQhd&quot;]/c-wiz[@class=&quot;PIlOad&quot;]/div[@class=&quot;Q5Eebb&quot;]/div[@class=&quot;IbUd0d&quot;]/h1[@class=&quot;BPNpve&quot;]</value>
      <webElementGuid>aeed694e-8b91-443d-9eff-bd2fc7c5cbd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz[2]/div/main/c-wiz/div/div/h1</value>
      <webElementGuid>8f320bd3-e72b-4cc6-b9b6-6fcd66a6c201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google News - Business - Latest'])[2]/following::h1[1]</value>
      <webElementGuid>fb969ba6-ee30-4925-84ec-fb1b300f656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google apps'])[1]/following::h1[1]</value>
      <webElementGuid>af31cfd0-a730-4900-9cad-806500d8d41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[8]/preceding::h1[1]</value>
      <webElementGuid>53871d6a-032d-428d-bbd7-12622e4cf475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest'])[1]/preceding::h1[1]</value>
      <webElementGuid>d0ed77da-1639-46ae-b0dc-fe6e8dbc38d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-wiz/div/div/h1</value>
      <webElementGuid>8e798c68-e2ae-4b84-9ede-33e85dda2683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Business' or . = 'Business')]</value>
      <webElementGuid>9eab0967-95c9-4a4f-950e-d1900164200a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
