<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Business</name>
   <tag></tag>
   <elementGuidId>8ef4c18d-ebbe-47d7-a81d-fbefd7c776c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='gb']/div[3]/div/c-wiz/div/div[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Business&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df60c5d0-bade-4963-bffa-cedab5c404e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brSCsc</value>
      <webElementGuid>fc20b81d-c60a-4684-9453-8f90ea34c172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>sCfAK</value>
      <webElementGuid>deda8294-9aba-4988-b33d-a6ece1e2bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Business</value>
      <webElementGuid>96d599d2-952c-46b8-a4e2-74fef7f852ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>54f8b6e7-8517-41bf-aef9-fd3080069852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4bf5f24-ea28-4405-bfbd-5089740f44ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./topics/CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAQ?hl=en-IN&amp;gl=IN&amp;ceid=IN%3Aen</value>
      <webElementGuid>ea81e584-55fb-403c-a844-40cae1feabf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business</value>
      <webElementGuid>806a50ea-5c97-4cab-a370-889d9320323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_a gb_qd&quot;]/div[1]/c-wiz[@class=&quot;Ax3bC IiQozc&quot;]/div[@class=&quot;VCnfNe&quot;]/div[@class=&quot;EctEBd&quot;]/a[@class=&quot;brSCsc&quot;]</value>
      <webElementGuid>7f21d48b-51e6-4277-bcde-3012d68d38be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gb']/div[3]/div/c-wiz/div/div[9]/a</value>
      <webElementGuid>44ba3367-4ec3-4f08-9c74-c1ac724977ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Business')]</value>
      <webElementGuid>f672cd95-ae11-4a4c-b2c8-e5e2cdefdb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local'])[1]/following::a[1]</value>
      <webElementGuid>07aae319-edf2-4f6a-8796-68f5ab16e992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World'])[1]/following::a[2]</value>
      <webElementGuid>980f1e8f-10cf-47c1-b2eb-cdf96ca5f46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::a[1]</value>
      <webElementGuid>38e044b5-4ce7-44b9-b8e8-642c19e0a6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entertainment'])[1]/preceding::a[2]</value>
      <webElementGuid>7599974d-1570-4fbd-9d01-ff4ed5213a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Business']/parent::*</value>
      <webElementGuid>527d450b-bc26-4af3-8eec-358560b330d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './topics/CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAQ?hl=en-IN&amp;gl=IN&amp;ceid=IN%3Aen')]</value>
      <webElementGuid>ab153db0-c550-4d3f-b074-7b325e8f6a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>35f549ab-8bf1-4460-a1c4-7214be28086f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './topics/CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKSlRpZ0FQAQ?hl=en-IN&amp;gl=IN&amp;ceid=IN%3Aen' and (text() = 'Business' or . = 'Business')]</value>
      <webElementGuid>4833e50e-dc29-420b-a2fb-b4b09c81ee5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
